/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_cqjtu_ets_onlinejudge_jni_JniApplication */

#ifndef _Included_com_cqjtu_ets_onlinejudge_jni_JniApplication
#define _Included_com_cqjtu_ets_onlinejudge_jni_JniApplication
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_cqjtu_ets_onlinejudge_jni_JniApplication
 * Method:    compile
 * Signature: (Lcom/cqjtu/ets/onlinejudge/jni/datastructure/JudgeConfig;)Lcom/cqjtu/ets/onlinejudge/jni/result/CompileResult;
 */
JNIEXPORT jobject JNICALL Java_com_cqjtu_ets_onlinejudge_jni_JniApplication_compile
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_cqjtu_ets_onlinejudge_jni_JniApplication
 * Method:    run
 * Signature: (Lcom/cqjtu/ets/onlinejudge/jni/datastructure/JudgeConfig;)Lcom/cqjtu/ets/onlinejudge/jni/result/ControllerResult;
 */
JNIEXPORT jobject JNICALL Java_com_cqjtu_ets_onlinejudge_jni_JniApplication_run
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_cqjtu_ets_onlinejudge_jni_JniApplication
 * Method:    check
 * Signature: (Lcom/cqjtu/ets/onlinejudge/jni/datastructure/JudgeConfig;)[Lcom/cqjtu/ets/onlinejudge/jni/result/CompareResult;
 */
JNIEXPORT jobjectArray JNICALL Java_com_cqjtu_ets_onlinejudge_jni_JniApplication_check
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
